---
count: 6
name: getopt-alt
default:
  restart: 0
  wait: 1
  env:
    PERL5LIB: lib:$PERL5LIB
editor:
  files:
    base:
      - lib/Getopt/Alt.pm
      - lib/Getopt/Alt/Option.pm
      - lib/Getopt/Alt/Command.pm
    helpers:
      - lib/Getopt/Alt/Dynamic.pm
      - lib/Getopt/Alt/Exception.pm
    docs:
      - lib/Getopt/Alt/Manual.pod
      - lib/Getopt/Alt/CookBook.pod
terminals:
  1a:
    wait: 0
    # watch is a list of files (or file groups) to watch for changes and
    # re-run the command. This watch waits for changes in files in the
    # lib bin and tests directories and then runs tests
    watch:
      - Build.PL
      - lib
      - bin
      - all-tests
    command: ./Build && ./Build testcover
  2:
    edit: base
  3:
    edit: helpers
  4:
    edit: docs
