---
abstract: "<One-line description of module's purpose>"
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GetOpt-Alt
provides:
  GetOpt::Alt:
    file: lib/GetOpt/Alt.pm
    version: v0.0.1
  GetOpt::Alt::Option:
    file: lib/GetOpt/Alt/Option.pm
    version: v0.0.1
requires:
  Config::Any: 0
  Moose: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
