---
abstract: 'Alternate method of processing command line arguments'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Alt
provides:
  Getopt::Alt:
    file: lib/Getopt/Alt.pm
    version: v0.0.1
  Getopt::Alt::Command:
    file: lib/Getopt/Alt/Command.pm
    version: v0.0.1
  Getopt::Alt::Option:
    file: lib/Getopt/Alt/Option.pm
    version: v0.0.1
requires:
  Config::Any: 0
  Moose: 0
  perl: 5.008
  version: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Getopt-Alt
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ivanwills/Getopt-Alt
version: v0.0.1
